// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!     DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU'RE DOING      !!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
//
//   It is generated from this file:
//     Source_Before_Replacements/./NeoFur/Public/NeoFurGameMode.h
//   Changes to this file will be overwritten. To change this file,
//   modify the file specified above and re-run RunPreprocessor.bsh.
//
//   Generation parameters:
//     NEO_FULLVERSION=1
//     NEO_FBX=1
//

// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "GameFramework/GameMode.h"
#include "NeoFurGameMode.generated.h"

/**
 *
 */
UCLASS()
class NEOFUR_API ANeoFurGameMode : public AGameMode
{
	GENERATED_BODY()
};
