// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!     DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU'RE DOING      !!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
//
//   It is generated from this file:
//     Source_Before_Replacements/./NeoFur/Public/NeoFurComputeShader.h
//   Changes to this file will be overwritten. To change this file,
//   modify the file specified above and re-run RunPreprocessor.bsh.
//
//   Generation parameters:
//     NEO_FULLVERSION=1
//     NEO_FBX=1
//

#pragma once

#include "NeoFur.h"
#include "NeoFurComponentSceneProxy.h"
#include "GlobalShader.h"

#ifndef NO_COMPUTE_SHADERS


struct FNeoFurComputeShaderPerFrameData
{
    uint32_t ControlPointCount;
    uint32_t ShellCount;
    uint32_t TotalShellCount;
    float ShellDistance;
    float DeltaTime;
    float ShellFade;
    FVector LocalSpaceGravity;
    FMatrix TransformFromLastFrame;
    float VisibleLengthScale;
};

// FIXME: Redundant name.
class FNeoFurComputeShaderCS : public FGlobalShader
{
	DECLARE_SHADER_TYPE(FNeoFurComputeShaderCS, Global);
public:

	// TODO: Make private?

	FShaderResourceParameter In_BoneMatrices;
	FShaderResourceParameter In_ControlPoints;
	FShaderResourceParameter In_OriginalMesh;
	FShaderResourceParameter In_MorphData;
	FShaderResourceParameter In_PhysicsProperties;

	FShaderResourceParameter Out_ControlPoints;
	FShaderResourceParameter Out_PostAnimVertexBuffer;

    FShaderResourceParameter In_PerFrameData;

	FNeoFurComputeShaderCS();
	explicit FNeoFurComputeShaderCS(const ShaderMetaType::CompiledShaderInitializerType &Initializer);

	static bool ShouldCache(EShaderPlatform Platform)
	{
		return RHISupportsComputeShaders(Platform);
	}

	virtual bool Serialize( FArchive& Ar ) override;

	static const TCHAR* GetSourceFilename();
	static const TCHAR* GetFunctionName();
};

#endif
